### ISSUE TITLE
Domain mapping

### ISSUE THREAD

**Issue by NICORUIZ06** [NICORUIZ06/CvGenerator#9]
All entities should be mapped as illustrated below:

![image](https://user-images.githubusercontent.com/45236258/90323486-4d85d300-df38-11ea-9e56-9130ec469115.png)

All mappings should be added in the **Domain** layer and in _DataContext_ class and inherits from _Entity_ base class.

**Comment by rambod17** [comment]
hello. can i work on it?
if yes, what is Actvie data type?

**Comment by NICORUIZ06** [comment]
Hi @rambod17 Nice to read you!

You are welcome to work on this!

Active property is a Boolean that determines if is visible or not.

Suggestions are welcome

Regards

**Comment by NICORUIZ06** [comment]
Thank you @rambod17 🥰
